CREATE DATABASE CYA_DATABASE;
USE CYA_DATABASE;
CREATE TABLE USERS (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CODE INT(9) NOT NULL,
    USERNAME VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(45) NOT NULL,
    IS_ADMIN BOOLEAN NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

INSERT INTO USERS (
    CODE,
    USERNAME,
    PASSWORD,
    IS_ADMIN,
    EMAIL
) VALUES (
    201611341,
    'cristian.fonseca03',
    'password',
    false,
    'cristian.lfs@gmail.com'
);

INSERT INTO USERS (
    CODE,
    USERNAME,
    PASSWORD,
    IS_ADMIN,
    EMAIL
) VALUES (
    2012456894,
    'juan.gonzales',
    'password',
    true,
    'juan.gonzalez@uptc.edu.co'
);

CREATE TABLE SUBJECTS (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(45) NOT NULL,
    CAREER VARCHAR(45) NOT NULL,
    CODE VARCHAR(10) NOT NULL
);

INSERT INTO SUBJECTS (
    NAME,
    CAREER,
    CODE
) VALUES (
    'Calculo 1',
    'Sistemas',
    '60-1'
);

INSERT INTO SUBJECTS (
    NAME,
    CAREER,
    CODE
) VALUES (
    'Calculo 1',
    'Sistemas',
    '60-2'
);

INSERT INTO SUBJECTS (
    NAME,
    CAREER,
    CODE
) VALUES (
    'programación 1',
    'Sistemas',
    '60-1'
);

INSERT INTO SUBJECTS (
    NAME,
    CAREER,
    CODE
) VALUES (
    'programación 2',
    'Sistemas',
    '60-1'
);

CREATE TABLE SUBJECTS_HISTORY (
    ID_USER INT NOT NULL,
    ID_SUBJECT INT NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES USERS(ID),
    FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECTS(ID)
);

INSERT INTO SUBJECTS_HISTORY VALUES (
    1,
    1
);

INSERT INTO SUBJECTS_HISTORY VALUES (
    1,
    3
);

INSERT INTO SUBJECTS_HISTORY VALUES (
    1,
    4
);

CREATE TABLE CANCELLATIONS (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    ID_SUBJECT INT NOT NULL,
    STATE VARCHAR(1) NOT NULL,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES USERS(ID),
    FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECTS(ID)
);

CREATE TABLE OPENINGS (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    ID_SUBJECT INT NOT NULL,
    STATE VARCHAR(1) NOT NULL,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES USERS(ID),
    FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECTS(ID)
);